# Generated by Django 5.1.6 on 2025-02-25 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='postcard',
            name='message',
        ),
        migrations.AddField(
            model_name='postcard',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postcard',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='postcard',
            name='image',
            field=models.ImageField(default='/static/cards/default.png', upload_to='postcards/'),
        ),
        migrations.AddField(
            model_name='postcard',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='postcard',
            name='categories',
            field=models.ManyToManyField(related_name='postcards', to='cards.category'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cards.postcard')),
            ],
        ),
    ]
