# Generated by Django 5.1.6 on 2025-02-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_category_remove_postcard_message_postcard_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcard',
            name='image',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='cards'),
        ),
    ]
