# Generated by Django 5.1.6 on 2025-02-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_materials_postcard_length_postcard_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='cards/'),
        ),
    ]
