# Generated by Django 5.1.6 on 2025-04-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='categories',
            field=models.ManyToManyField(related_name='postcards', to='cards.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана :'),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание открытки'),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длинна'),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='materials',
            field=models.ManyToManyField(related_name='postcards', to='cards.materials', verbose_name='Материалы'),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена открытки'),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название открытки'),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена :'),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
    ]
