# Generated by Django 5.1.6 on 2025-04-01 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='patronymic',
            new_name='middle_name',
        ),
    ]
