# Generated by Django 5.1.6 on 2025-04-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_patronymic_customuser_middle_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
