# Generated by Django 5.1.6 on 2025-04-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_postcard_available_alter_postcard_categories_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postcards',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='cards.postcard'),
        ),
    ]
