# Generated by Django 5.1.6 on 2025-04-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_postcard_available_alter_postcard_categories_and_more'),
        ('orders', '0002_alter_order_postcards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_id',
            new_name='payment',
        ),
        migrations.AlterField(
            model_name='order',
            name='postcards',
            field=models.ManyToManyField(blank=True, related_name='orders', to='cards.postcard'),
        ),
    ]
