# Generated by Django 5.1.6 on 2025-04-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_payment_id_order_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sdek_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sdek_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
