# Generated by Django 5.1.6 on 2025-04-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_sdek_id_order_sdek_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sdek_status',
            new_name='sdek_number',
        ),
    ]
