# Generated by Django 5.1.6 on 2025-03-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_self', models.BooleanField(default=False)),
                ('delivery_address', models.JSONField(blank=True, null=True)),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_office', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_tariff_code', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_name', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_office_detail', models.JSONField(blank=True, null=True)),
                ('min_delivery_time', models.TimeField(blank=True, null=True)),
                ('max_delivery_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
