# Generated by Django 5.1.6 on 2025-03-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='max_delivery_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='min_delivery_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
