# Generated by Django 5.1.6 on 2025-04-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='idempotence_key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
